# Generated by Django 5.2.10 on 2026-02-18 13:04

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Centre géométrique du cluster",
                        srid=4326,
                        verbose_name="Centroïde",
                    ),
                ),
                (
                    "report_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de signalements"
                    ),
                ),
                (
                    "max_danger_level",
                    models.CharField(
                        choices=[
                            ("green", "Déchets verts"),
                            ("household", "Déchets ménagers"),
                            ("bulky", "Encombrants"),
                            ("chemical", "Déchets chimiques"),
                            ("asbestos", "Amiante"),
                        ],
                        default="green",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cluster",
                "verbose_name_plural": "Clusters",
                "ordering": ["-report_count"],
            },
        ),
        migrations.AddField(
            model_name="report",
            name="cluster",
            field=models.ForeignKey(
                blank=True,
                help_text="Cluster de signalements proches",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="reports.reportcluster",
                verbose_name="Cluster",
            ),
        ),
    ]
