# Generated by Django 5.2.10 on 2026-02-18 14:50

from django.contrib.gis.measure import D
from django.db import migrations


def cluster_existing_reports(apps, schema_editor):
    """Regroupe les signalements existants en clusters (≤10m)."""
    Report = apps.get_model("reports", "Report")
    ReportCluster = apps.get_model("reports", "ReportCluster")

    for report in Report.objects.order_by("created_at"):
        # Chercher les clusters proches (≤10m)
        nearby = ReportCluster.objects.filter(
            centroid__dwithin=(report.location, D(m=10))
        )
        nearby_list = list(nearby)

        if len(nearby_list) == 0:
            # Créer un nouveau cluster
            cluster = ReportCluster.objects.create(
                centroid=report.location,
                report_count=1,
                max_type=report.type,
            )
            Report.objects.filter(pk=report.pk).update(cluster=cluster)

        elif len(nearby_list) == 1:
            # Ajouter au cluster existant
            cluster = nearby_list[0]
            Report.objects.filter(pk=report.pk).update(cluster=cluster)
            # Recalculer count et danger (pas de Centroid dispo dans RunPython)
            cluster.report_count = cluster.reports.count()
            # Max danger
            from reports.models import DANGER_SEVERITY

            levels = list(cluster.reports.values_list("type", flat=True))
            if levels:
                cluster.max_type = max(levels, key=lambda d: DANGER_SEVERITY.get(d, 0))
            cluster.save()

        else:
            # Fusionner les clusters puis ajouter
            from reports.models import DANGER_SEVERITY

            ordered = sorted(nearby_list, key=lambda c: c.created_at)
            main_cluster = ordered[0]
            others = ordered[1:]

            for other in others:
                other.reports.update(cluster=main_cluster)
            ReportCluster.objects.filter(pk__in=[c.pk for c in others]).delete()

            Report.objects.filter(pk=report.pk).update(cluster=main_cluster)
            main_cluster.report_count = main_cluster.reports.count()
            levels = list(main_cluster.reports.values_list("type", flat=True))
            if levels:
                main_cluster.max_type = max(
                    levels, key=lambda d: DANGER_SEVERITY.get(d, 0)
                )
            main_cluster.save()


def reverse_clustering(apps, schema_editor):
    """Supprime tous les clusters et détache les signalements."""
    Report = apps.get_model("reports", "Report")
    ReportCluster = apps.get_model("reports", "ReportCluster")
    Report.objects.all().update(cluster=None)
    ReportCluster.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_reportcluster_report_cluster"),
    ]

    operations = [
        migrations.RunPython(cluster_existing_reports, reverse_clustering),
    ]
