# Generated by Django 5.2.10 on 2026-02-21 11:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0003_recluster_existing_reports"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="type",
            field=models.CharField(
                choices=[
                    ("green", "Déchets verts"),
                    ("household", "Déchets ménagers"),
                    ("bulky", "Encombrants"),
                    ("chemical", "Déchets chimiques"),
                    ("asbestos", "Amiante"),
                    ("building", "Construction"),
                ],
                help_text="Type de déchets et danger associé",
                max_length=20,
                verbose_name="Niveau de dangerosité",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                geography=True,
                help_text="Position GPS du dépôt",
                srid=4326,
                verbose_name="Localisation",
            ),
        ),
        migrations.AlterField(
            model_name="reportcluster",
            name="centroid",
            field=django.contrib.gis.db.models.fields.PointField(
                geography=True,
                help_text="Centre géométrique du cluster",
                srid=4326,
                verbose_name="Centroïde",
            ),
        ),
    ]
