# Generated by Django 5.2.10 on 2026-02-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0004_alter_report_danger_level_alter_report_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportcluster",
            name="max_danger_level",
        ),
        migrations.AddField(
            model_name="reportcluster",
            name="max_waste_type",
            field=models.CharField(
                choices=[
                    ("green", "Déchets verts"),
                    ("household", "Déchets ménagers"),
                    ("bulky", "Encombrants"),
                    ("building", "Construction"),
                    ("chemical", "Déchets chimiques"),
                    ("asbestos", "Amiante"),
                ],
                default="green",
                max_length=20,
                verbose_name="Catégorie dominante",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="type",
            field=models.CharField(
                choices=[
                    ("green", "Déchets verts"),
                    ("household", "Déchets ménagers"),
                    ("bulky", "Encombrants"),
                    ("building", "Construction"),
                    ("chemical", "Déchets chimiques"),
                    ("asbestos", "Amiante"),
                ],
                help_text="Type de déchets déposés",
                max_length=20,
                verbose_name="Catégorie de déchets",
            ),
        ),
    ]
